version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env.mainnet
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/2024-04-09-133747_create_user/up.sql:/docker-entrypoint-initdb.d/up.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      start_period: 5s

    env_file:
      - .env