// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

// use 
use chrono::NaiveDateTime;
use serde::Serialize;
use uuid::Uuid;
use diesel::{ sql_types::SqlType, QueryId, Queryable, Selectable, QueryableByName };
// use diesel::query_builder::SqlQuery;

#[derive(Queryable, Debug)]
pub struct Confirmation {
    pub id: Uuid,
    pub email: String,
    pub expires_at: NaiveDateTime,
}
#[derive(Queryable, Debug, QueryId, SqlType, Serialize, PartialEq)]
pub struct User {
    pub id: Uuid,
    pub email: String,
    pub name: String,
    pub hashed_password: String,
}
